# syntax=docker/dockerfile:1

FROM golang:1.18 AS build

ARG test_dir
WORKDIR /app

COPY go.sum go.mod ./
RUN go install -v ./...

COPY . ./

RUN go test -c -v ./tests/$test_dir -o /pkg.test

##
## Deploy
##
FROM gcr.io/distroless/base-debian10
WORKDIR /
COPY --from=build /pkg.test /pkg.test

CMD ["/pkg.test", "-test.v"]